#!/bin/sh
. /etc/functions.sh
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
[ -z "$PPP_IPPARAM" -o -z "$PPP_LOCAL" ] || {
	uci_set_state network "$PPP_IPPARAM" ifname "$PPP_IFACE"
	uci_set_state network "$PPP_IPPARAM" ipaddr "$PPP_LOCAL"
	uci_set_state network "$PPP_IPPARAM" gateway "$PPP_REMOTE"

	defgw=`ip route list dev $PPP_IFACE |grep default`
	if [ -n "$defgw" ] ; then
	   gw="${defgw#*via }"
	   gw="${gw%% *}"
	   [ "$gw" != "$PPP_REMOTE" ] && {
	     ip route del $defgw                                                
	     ip route append default via $PPP_REMOTE dev $PPP_IFACE metric 1       
	   }
	else
   	   ip route append default via $PPP_REMOTE dev $PPP_IFACE metric 1
	fi

}
[ -z "$PPP_IPPARAM" ] || env -i ACTION="ifup" INTERFACE="$PPP_IPPARAM" DEVICE="$PPP_IFACE" PROTO=ppp /sbin/hotplug-call "iface"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" $@
	done
}

#re-evaluate dnsmasq dynamic settings
. /bin/dns_eval.sh
dns_evaluate "pppup:$PPP_IFACE"

