#!/bin/sh
# Copyright (C) 2006 OpenWrt.org


debug_hotplug=0
hotplug_file=/tmp/hotplug.log

[ -f /tmp/debug_hotplug ] && {
  debug_hotplug=1
  echo "hotplug[$0 $@] started at $(date)" >> $hotplug_file
}

dbg_log() {
  [ $debug_hotplug = 1 ] && echo "$@" >> $hotplug_file
}


export HOTPLUG_TYPE="$1"

# bypass the normal hotplug path for firmware loading
# would otherwise cause problems with drivers like bcm43xx
[ "firmware" = "$HOTPLUG_TYPE" -a "add" = "$ACTION" ] && {
	[ -f "/lib/firmware/$FIRMWARE" ] && {
		echo 1 > "/sys$DEVPATH/loading"
		cp "/lib/firmware/$FIRMWARE" "/sys$DEVPATH/data"
		echo 0 > "/sys$DEVPATH/loading"
	}
	exit 0
}

. /etc/functions.sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LOGNAME=root
USER=root
export PATH LOGNAME USER

[ \! -z "$1" -a -d /etc/hotplug.d/$1 ] && {
	for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
		dbg_log "$script $2 ACTION=$ACTION INTERFACE=$INTERFACE DEVICE=$DEVICE PROTO=$PROTO STATE=$STATE" >> /tmp/hotplug.log
		[ -f $script ] && . $script "$2"
	); done
}
