#!/bin/sh

name=wps_hrg

pressed() {
	logger -s -t $name "hostapd_cli -i ath0 -p /var/run/hostapd wps_pbc"
	if hostapd_cli -i ath0 -p /var/run/hostapd wps_pbc | grep -q OK; then
		logger -s -t $name "WPS PBC mode is started with success"
	fi
}

client_pin() {
	# To reduce likelihood of PIN being used with other devices or of
	#   forgetting an active PIN available for potential attackers, expiration
	#   time in seconds can be set for the new PIN
	logger -s -t $name "hostapd_cli -i ath0 -p /var/run/hostapd wps_pin any $1 300"
	if hostapd_cli -i ath0 -p /var/run/hostapd wps_pin any $1 300 | grep -q OK; then
		logger -s -t $name "WPS PIN mode is started with success"
	fi
}

case "$1" in
		# TODO: case 2 will be for wifi1 (second wireless card)
		1|2|pbc) pressed;;

		# Since the caller script network-wps.sh checks for pin, directly use it here.
		pin) client_pin $2;;
		
		*) break;;
esac
