#!/bin/sh /etc/rc.common
#
# Copyright (C) 2012 Genexis BV. All rights reserved
# Copyright (C) 2010,2011 Packetfront International AB. All rights reserved

START=75
CATV_MONITOR=catvmonitor

set_default_config() {  
  /sbin/uci setdefault /etc/config/catv.global.enable="0"
  /sbin/uci setdefault /etc/config/catv.global.filter="1"
}

start() {
  local enable=`/sbin/uci get catv.global.enable`
  local filter=`/sbin/uci get catv.global.filter`

  echo "Starting CATV initialization"

  # Configure the CATV hardware into the required state
  echo $enable > /proc/gpio/control/catv_enable
  echo $filter > /proc/gpio/control/catv_filter

  if pidof $CATV_MONITOR > /dev/null; then
      echo "Warning, a $CATV_MONITOR process is already running!"
      exit 1
  fi

  /usr/bin/$CATV_MONITOR &

  return 0
}

stop() {
  killall $CATV_MONITOR 2>/dev/null

  # Disable CATV hardware - ensures in clean state, i.e. disabled if the 
  # service is stopped for any reason
  echo '0' > /proc/gpio/control/catv_enable
  echo '1' > /proc/gpio/control/catv_filter

  return 0
}

restart() {
  stop
  start

  return 0
}

