#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=92
STOP=9
boot() {
	[ -d /tmp/root ] && {
		lock /tmp/.switch2jffs
		firstboot switch2jffs
		lock -u /tmp/.switch2jffs
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done

}

start() {
    echo 1 > /proc/gpio/led/status
        
    #enable  management framework
    pid=`pidof ma`
    kill -SIGHUP $pid 
    
    
    # Allow switch ports to go up
    touch /tmp/boot_done
    /etc/init.d/switch reload
}

stop() {
    echo 0 > /proc/gpio/led/status
    
}

