#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=50
# Copyright (C) 2006 Carlos Sobrinho

config_cb() {
	local cfg="$CONFIG_SECTION"
	local nopasswd
	local cfgt

	config_get cfgt "$cfg" TYPE

	case "$cfgt" in
		dropbear)
			config_get passauth $cfg PasswordAuth
			config_get port $cfg Port

			case "$passauth" in
				no|off|disabled|0) nopasswd=1;;
			esac

			DROPBEAR_ARGS="${nopasswd:+-s }${port:+-p $port}"
		;;
	esac
}

keygen() {
	for keytype in rsa dss; do
		# check for keys
		key=dropbear/dropbear_${keytype}_host_key
		[ -f /tmp/$key -o -f /etc/$key ] || {
			# generate missing keys
			mkdir -p /tmp/dropbear
			[ -x /usr/bin/dropbearkey ] && {
				/usr/bin/dropbearkey -t $keytype -f /tmp/$key 2>&- >&- && exec /etc/rc.common "$initscript" start
			} &
		exit 0
		}
	done

	lock /tmp/.switch2jffs
	mkdir -p /etc/dropbear
	mv /tmp/dropbear/dropbear_* /etc/dropbear/
	lock -u /tmp/.switch2jffs
	chown root /etc/dropbear
	chmod 0700 /etc/dropbear
}

set_default_config()
{
	local uci_confdir="/etc/config/"
	local cfg="dropbear"

	/sbin/uci setdefault $uci_confdir/$cfg.dropbear.PasswordAuth="on"
	/sbin/uci setdefault $uci_confdir/$cfg.dropbear.Port=22
}

check_config_dir() {
	# copy key files from persistent directory if they exist
	cdir=/config/.dropbear
	edir=/etc/dropbear
	[ -d $edir ] || { mkdir $edir; chmod 0700 $edir; }
	for f in dropbear_rsa_host_key dropbear_dss_host_key authorized_keys; do
	    if [ -f $cdir/$f -a ! -f $edir/$f ]; then
		cp -f $cdir/$f $edir/$f
	    fi
	done
}

check_usp() {
	# generate key files from USP if information exists
	local uci_configdir="/etc/config"
	local cfg="usp"
	local edir="/etc/dropbear"

	[ -d $edir ] || { mkdir $edir; chmod 0700 $edir; }
	for keytype in rsa dss ; do
	    if [ ! -f $edir/dropbear_${keytype}_host_key ]; then
		/sbin/uci get $uci_configdir/$cfg.dropbear.${keytype}key > /tmp/$keytype.key.b64
		if [ -s /tmp/$keytype.key.b64 ]; then
			base64 -d /tmp/$keytype.key.b64 > $edir/dropbear_${keytype}_host_key
			rm /tmp/$keytype.key.b64
		fi
	    fi
	done
}
    
prepare() {
    check_usp
    check_config_dir
    [ -f /etc/dropbear/dropbear_rsa_host_key -a \
	-f /etc/dropbear/dropbear_dss_host_key ] || keygen    
    config_load dropbear
}


stop() {
    ps | while read arg1 arg2 arg3 arg4 arg5 arg6 arg7; do
	[ "$arg5" = "/usr/sbin/dropbear" ] && kill $arg1
    done
}

drpfile=/tmp/dropbear.args
reload() {
    equal=

    prepare
   
    [ -f $drpfile ] && {
	while read line;do
	    [ "$line" = "$DROPBEAR_ARGS" ] && equal=true
	done < $drpfile
	#exit child process
	exit
    }

    [ -z $equal ] && {
	stop
	/usr/sbin/dropbear $DROPBEAR_ARGS
	echo "$DROPBEAR_ARGS" > $drpfile
	sync
    }
    
}



start() {
    stop
    prepare
    /usr/sbin/dropbear $DROPBEAR_ARGS
    echo "$DROPBEAR_ARGS" > $drpfile
    sync
}

restart() {
    start
}
