#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50
STOP=90
HTTPD_BIN="/usr/sbin/httpd"

system_config() {
	local cfg="$1"

	config_get hostname "$cfg" hostname
}

httpd_config() {
	local cfg="$1"
	local c_file port realm home args

	config_get c_file "$cfg" c_file
	[ -n "$c_file" -a -f "$c_file" ] && append args "-c \"$c_file\""
	config_get port "$cfg" port
	append args "-p ${port:-80}"
	config_get home "$cfg" home
	home="${home:-/www}"
	[ -d "$home" ] || return 1
	append args "-h \"$home\""
	config_get realm "$cfg" realm
	realm="${realm:-$hostname}"
	append args "-r \"$realm\""
	eval "$HTTPD_BIN $args"
}

set_default_config()
{
	local uci_confdir="/etc/config/"
	local cfg="httpd"

	/sbin/uci setdefault $uci_confdir/$cfg.httpd.port=80
	/sbin/uci setdefault $uci_confdir/$cfg.httpd.home="/www"
}

start() {
	[ -x "$HTTPD_BIN" ] || return 1

	unset hostname
	config_load system
	config_foreach system_config system
	hostname="${hostname:-drgos}"

	unset args
	config_load httpd
	[ "$?" != "0" ] && {
		config_load httpd
	}
	config_foreach httpd_config httpd
}

stop() {
	kill `ps | grep $HTTPD_BIN | grep -v grep | awk '{ print $1 }'`
        sleep 1
	kill -9 `ps | grep $HTTPD_BIN | grep -v grep | awk '{ print $1 }'`
}

restart() {
	stop
	sleep 1
	start
}

