#!/bin/sh /etc/rc.common
START=79
start() {
  config_load "upnpd"
  config_get upnp_enable config enabled 
  [ "$upnp_enable" -eq 1 ] && {
    include /lib/network
    scan_interfaces

    echo "miniupnpd starting ..."
    stop

    config_get ifname config wan_interface
    [ -z "$ifname" ] && {
      config_get ifname default wan_if
    }

    [ -n "$ifname" ] && {
      ifname=`uci get -P /var/state network.${ifname//\"/}.ifname`
    }

    config_get lan_ifname config lan_interface
    [ -n "$lan_ifname" ] && {
      lan_ifname=`uci get -P /var/state network.${lan_ifname//\"/}.ifname`
    }
    [ -z "$lan_ifname" ] && {
      config_get lan_ifname lan ifname
    }

    iptables_init.sh 2>&- >&-
    # get bitspeed information, if provided
    config_get upnp_up_bitspeed config upload
    config_get upnp_down_bitspeed config download
    bitspeed_str=""
    [ -n "$upnpd_up_bitspeed" ] && [ -n "$upnpd_down_bitspeed" ] && {
      # covert to bytespeed
      upnpd_up_bytespeed=$(($upnpd_up_bitspeed * 1024 / 8))
      upnpd_down_bytespeed=$(($upnpd_down_bitspeed * 1024 / 8))
      bitspeed_str="-B $upnpd_down_bytespeed $upnpd_up_bytespeed"
    }
    config_get log_output config log_output
    if [ "$log_output" = "1" ]; then
      miniupnpd -i "$ifname" -n "$lan_ifname" -p 5000 -U $bitspeed_str -d | logger -t miniupnpd &
    else
      miniupnpd -i "$ifname" -n "$lan_ifname" -p 5000 -U $bitspeed_str
    fi

  }
}

stop() {
  pnpd_pid=$(cat /var/run/miniupnpd.pid) 2>&- >&-
  iptables_flush.sh 2>&- >&-
  kill $pnpd_pid 2>&-
  iptables_removeall.sh 2>&- >&-
}
