#!/bin/sh /etc/rc.common

START=22

CONF_USER=/config/.ox-user-config
CONF_OPER=/config/.ox-startup-config

start () {
    #start daemon to handle multi lan support in 1.6.1
    #according to IP
    pmlh&
    if [ -f $CONF_USER ]; then
	/usr/bin/oxsh -u -c $CONF_USER
    fi

    if [ -f $CONF_OPER ]; then
	/usr/bin/oxsh -c $CONF_OPER
    fi
}

