#!/bin/sh
# Copyright (C) 2006 OpenWrt.org


{
    for i in /etc/rc.d/S*; do
	[ -x $i ] && $i set_default_config >/dev/null 2>&1
    done 
    
    for i in /etc/rc.d/S*; do
	[ -x $i ] && $i start 2>&1
    done | logger -p 6 -t sysinit
} &
