#!/bin/sh /etc/rc.common

START=01

start() {

	revision=`grep '^Revision[[:space:]]*:' /proc/cpuinfo | cut -d: -f2`
	c1000=`grep '^Hardware[[:space:]]*: Comcerto 1000' /proc/cpuinfo`

	[ -d /lib/modules/`uname -r` ] && {
		cd /lib/modules/`uname -r`
		for module_revc in `find ./ -name "*_revc.ko"`; do
			module_revb=`echo $module_revc | sed s/_revc/_revb/ -`

			[ -f $module_revb ] && {
				module=`echo $module_revc | sed s/_revc// -`

				if [ -n "$c1000" ]; then
					rm -f $module
					ln -s $module_revc $module
				else
					if [ $revision -eq "0002" ]; then
						rm -f $module
						ln -s $module_revc $module
					else
						rm -f $module
						ln -s $module_revb $module
					fi
				fi
			}
		done;
	}
}
