#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=35
STOP=35

set_default_config() {
    #create default config
    [ -s /etc/config/switch ] || switch config
}
boot() {
    
    #create default config
    [ -s /etc/config/switch ] || switch config
    
    insmod external_switch

    switch setup
}

start() {

    #create default config
    [ -s /etc/config/switch ] || switch config

    switch setup
}

restart() {
    switch setup
}

reload() {
    switch setup
}

stop() 
{
    switch down
}
