#!/bin/sh /etc/rc.common
START=01
start () {
    mkfifo /dev/sysload 2>/dev/null
    
    /sbin/sysloadd >/dev/null 2>&1 &
}

stop () {
    killall -9 sysloadd 2>/dev/null
}

restart () {
   stop
   start
}

reload() {                                                    
  restart                                                     
}
