#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=89
TR069CLIENT=cwmpclient
CONFDIR="/tmp/cpe3"

# logfile=$CONFDIR/tr069-cwmp.log
logfile="/dev/null"


set_default_config() {
    local uci_confdir="/etc/config"
    local cfg="tr069_client"

    local client=$cfg."client"
    /sbin/uci setdefault $uci_confdir/$client="cwmp"
    /sbin/uci setdefault $uci_confdir/$cfg.client.binary="$TR069CLIENT"
    /sbin/uci setdefault $uci_confdir/$cfg.client.enable="1"  >/dev/null

    local srv=$cfg."management_server"
    /sbin/uci setdefault $uci_confdir/$srv="cwmp"
    /sbin/uci setdefault $uci_confdir/$srv.url="" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.username="" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.password="" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.connection_request_username="" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.connection_request_password="" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.interval="86400" >/dev/null
    /sbin/uci setdefault $uci_confdir/$srv.UpgradesManaged="0" >/dev/null

    local dev=$cfg."device_info"
    /sbin/uci setdefault $uci_confdir/$dev="cwmp"

    local manufacturer=$(uci -q get usp.product.manufacturer)
    /sbin/uci setdefault $uci_confdir/$dev.manufacturer="${manufacturer:-Genexis BV}" >/dev/null

    /sbin/uci setdefault $uci_confdir/$dev.manufacturer_oui="000F5D" >/dev/null

}

config_load() {
	[ -d "$CONFDIR" ] || exit
	cp -f /etc/dps.param $CONFDIR/ || exit
# Always do a fresh start. dimclient doesn't change this file anyway.
}

start() {
    if pidof $TR069CLIENT >/dev/null; then
        echo "Warning, a $TR069CLIENT is already running!"
        exit 1
    fi

    echo -n Starting TR-069 client daemon..

    local enable=`/sbin/uci get tr069_client.client.enable`
    if [ $enable != "1" ]; then
       echo "TR-069 client is disabled."
       exit 1
    fi

    CONFDIR="/tmp/cpe3"

    if [ ! -d "$CONFDIR" ]; then
	rm -rf "$CONFDIR"
	mkdir -p "$CONFDIR"
    fi
 
    if ! cd "$CONFDIR" ; then
	echo could not cd to $CONFDIR
	exit 1
    fi
    
    for dir in data filetrans options parameter; do
	if [ ! -d "$dir" ]; then
	    rm -rf "$dir"
	    mkdir -p "$dir"
	fi
    done

    if [ -d /config/tr069/filetrans/ ] ; then
       fs_lock 30
       if [ $? -eq 0 ] ; then 
          for file in /config/tr069/filetrans/* ; do
             mv $file filetrans
          done
          rm -rf /config/tr069/filetrans

          fs_unlock
      fi
    fi

    if [ -f /config/tr069/eventCode.dat ]; then
       fs_lock 30
       if [ $? -eq 0 ]; then
          mv /config/tr069/eventCode.dat eventCode.dat

          rm -rf /config/tr069/eventCode.dat

          fs_unlock
       fi
    fi

    config_load >>$logfile 2>&1

    (cd "$CONFDIR" && $TR069CLIENT) </dev/null >>$logfile 2>&1 &

    echo  ...done at `date`

    return 0
}

stop() {
    echo Stopping TR-069 client daemon

    killall $TR069CLIENT 2>/dev/null
    pidof $TR069CLIENT >/dev/null && sleep 3

    while pidof $TR069CLIENT >/dev/null; do
        killall -KILL $TR069CLIENT 2>/dev/null
    	sleep 2
    done

    return 0
}

restart() {
    local enable=`/sbin/uci get tr069_client.client.enable`
    if [ $enable != "1" ]; then
        pidof $TR069CLIENT >/dev/null && stop

        return 0
    fi

    # Restarted by management framework
    if grep -q "/etc/apply" /proc/$PPID/cmdline && pidof $TR069CLIENT ; then
        local acs_url=`/sbin/uci get tr069_client.management_server.url`
        local acs_url1=`/sbin/uci get /config/tr069/tr069_client.cwmp.acs_server`

        [ $acs_url == $acs_url1 ] && return 0
    fi

    echo Restarting TR-069 client daemon

    pidof $TR069CLIENT >/dev/null && stop
    start

    return 0
}

