#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org
set_default_config() {
  local uci_confdir="/etc/config"
  local cfg="tr104"
}

start() {
  return 0
}

stop() {
  return 0
}

reload() {
  return 0
}

restart() {
  return 0
}
