#!/bin/sh /etc/rc.common

#
# read uci user config and create unix and webif user accounts
#

START=67
. /etc/functions.sh
. /lib/config/uci.sh

do_user() {
    local user="$1"

    config_get disabled "$user" disabled
    [ "$disabled" != 1 ] || return 0

    config_get password "$user" password
    [ -n "$password" ] || return 0

    config_get ash "$user" ash
    config_get cli "$user" cli
    config_get gui "$user" gui
    if [ -n "$ash" ]; then
	echo "$user:$password:0:0:root:/root:/bin/ash" >> $npass
    elif [ -n "$cli" ]; then
	echo "$user:$password:0:0:root:/root:/usr/bin/oxsh" >> $npass
    fi
    if [ -n "$gui" ]; then
	echo "/:$user:$password" >> $ngui
    fi
}

start() {
	config_load user

	# save the standard users like nobody and daemon
	[ -f /etc/passwd.std ] || cp /etc/passwd /etc/passwd.std

	# make temp files
	npass=`mktemp /tmp/passwd.XXXXXX`
	ngui=`mktemp /tmp/gui.XXXXXX`

	# for each user add entry if configured
	config_foreach do_user user

	# update /etc/passwd if needed
	if ! cmp -s /etc/passwd $npass; then
	    cat /etc/passwd.std $npass > /etc/passwd
	fi
	rm -f $npass

	# update /etc/web.passwd if needed
	if ! cmp -s /etc/webif.passwd $ngui; then
	    mv $ngui /etc/webif.passwd
	    if [ -s /etc/webif.passwd ]; then
		/etc/init.d/webif restart
	    else
		/etc/init.d/webif stop
	    fi
	else
	    rm $ngui
	fi
}

reload() {
	start
}
