#!/bin/sh /etc/rc.common
# Copyright (c) 2009 Packetfront Systems AB

START=01


MTD_USP_NUM=`cat /proc/mtd |grep ^mtd |grep -n UniqueParam |cut -d':' -f 1`
if [ ! -z "$MTD_USP_NUM" ] ; then
  MTD_USP_NUM=$((MTD_USP_NUM-1))
else
  MTD_USP_NUM=4 # Default USP mtdblock device node for DRG600P
fi

MTD_USP_NODE="/dev/mtd$MTD_USP_NUM"

mapping_usp() {
  LINE_COUNT=`dd if=$MTD_USP_NODE 2>/dev/null | wc -l`
  dd if=$MTD_USP_NODE 2>/dev/null | head -n $LINE_COUNT >/etc/config/usp
}

set_default_config() {
    mapping_usp
}

