#!/bin/sh /etc/rc.common
# Modified for OpenWRT environment by Packetfront Systems AB

START=12
STOP=

# Source function library.
. /etc/functions.sh

VERBOSE="no"
if [ -f /etc/sysconfig/watchdog ]; then
    . /etc/sysconfig/watchdog
fi

RETVAL=0
prog=watchdog
pidfile=/var/run/watchdog.pid
lockfile=/var/lock/watchdog

start() {

	echo -n "Starting $prog: "
	if [ -n "$(pidof -o $$ $prog)" ]; then
	  echo "already running - Failure"
	  return 1
	fi

	if [ ! -f /etc/watchdog.conf ]; then
	  echo "Missing config - Failure"
	  return 1
	fi

	if [ "$VERBOSE" = "yes" ]; then
	    /usr/sbin/${prog} -v &
	else
	    /usr/sbin/${prog} &
        fi
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $lockfile
	[ $RETVAL -eq 0 ] && echo "Success"
	[ $RETVAL -ne 0 ] && echo "Failure"
	return $RETVAL
}

stop() {
	echo -n "Stopping $prog: "
	# We are forcing it to _only_ use -TERM as killproc could use
	# -KILL which would result in BMC timer not being set properly 
	# and reboot the box.
	killall -SIGTERM $prog 2> /dev/null
	RETVAL=$?
	[ $RETVAL -eq 0 ] && echo "Success"
	[ $RETVAL -ne 0 ] && echo "Failure"
	[ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
	return $RETVAL
}

restart() {
  	stop
	sleep 6
	start
}	

