#!/bin/sh /etc/rc.common

#this script should not run at boot time. It is only used by highlevel 
#protocols when wifi should be reloaded.
#As default Wifi is restarted in init.d/network script

#START=45
#STOP=45

#boot() {    
#}

#start() {
#}

restart() {
    wifi up
}


#stop() {
#}
