#!/bin/sh
[ "$ACTION" = "ifup" ] && {

   upnp_enabled=`uci get upnpd.config.enabled`

   [ "$upnp_enabled" = "1" ] && {

      wanif=`uci get upnpd.config.wan_interface`
      [ -z "$wanif" ] && {
        wanif=`uci get network.default.wan_if`
      }

      [ "$INTERFACE" = "$wanif" ] && /etc/init.d/miniupnpd restart
   }
}
