#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh

NTP_ROUTE_FILE="/tmp/ntp_route"

get_src_if() {
  unset SRC_IF

  config_load ntpclient

  config_get old_dhcp_opt42 general dhcp_opt42

  config_get SRC_IF general src_if

  # if no ntp source-interface, then try mgmt src interface
  [ -z "$SRC_IF" ] && SRC_IF=`uci -q get route.mgmt_src_if`

  # if no mgmt src interface, then try wan interface
  [ -z "$SRC_IF" ] && SRC_IF=`uci -q get network.lan.natexternaliface`
  [ -z "$SRC_IF" ] && SRC_IF=`uci -q get network.default.wan_if`
}

stop_ntpclient() {
  logger stopping ntpclient
  killall -KILL ntpclient

  [ -f $NTP_ROUTE_FILE ] && old_ntp_route=`cat $NTP_ROUTE_FILE`
  [ -n "$old_ntp_route" ] && route del ${old_ntp_route%%[[:blank:]]*.*}
}

#only proceed if opt42 come from right source interface
get_src_if
[ -n "$SRC_IF" ] && [ "$INTERFACE" = "$SRC_IF" ] && {

    case "${ACTION:-ifup}" in
	ifup)
		echo "ntpclient.general.dhcp_opt42=$1" > /tmp/mafifo
	;;
	update)
		[ "pf$old_dhcp_opt42" != "pf$1" ] && {
			echo "ntpclient.general.dhcp_opt42=$1" > /tmp/mafifo
		}
	;;
	ifdown)
		stop_ntpclient
	;;
    esac
}
